version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Sao_Paulo"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
      major:
        update-types: ["major"]
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Sao_Paulo"
    groups:
      actions:
        patterns: ["*"]
